'use strict';
/* NEBULA PROTOCOL v9 — dynamic procedural war events integrated with the existing wave loop. */
(()=>{
  const N8=window.N8,V=N8.v9,hook=N8.hook,rnd=N8.rnd;
  const defs=[
    {id:'INVASION',name:'FLEET INVASION',objective:'Destroy 18 invasion ships',type:'kills',goal:18,reward:420,time:900,color:'#ff5f5f',spawn:['INTERCEPTOR','FIGHTER','BOMBER'],effect:'reinforcements'},
    {id:'PIRATE',name:'PIRATE RAID',objective:'Destroy 12 raiders',type:'kills',goal:12,reward:360,time:780,color:'#ff9d2e',spawn:['BOMBER','ASSASSIN','HUNTER'],effect:'agile'},
    {id:'DISTRESS',name:'DISTRESS SIGNAL',objective:'Hold the distress corridor for 90 seconds',type:'survive',goal:90,reward:520,time:5400,color:'#5ec8ff',spawn:['FIGHTER','SHIELD_DRONE'],effect:'escort'},
    {id:'CONVOY',name:'CONVOY AMBUSH',objective:'Protect the convoy until extraction',type:'survive',goal:105,reward:600,time:6300,color:'#ffe066',spawn:['BOMBER','INTERCEPTOR','HUNTER'],effect:'convoy'},
    {id:'CAPITAL',name:'CAPITAL SHIP ASSAULT',objective:'Destroy the hostile capital ship',type:'capital',goal:1,reward:1000,time:2400,color:'#d98cff',spawn:['ELITE','FIGHTER'],effect:'capital'},
    {id:'ASTEROID',name:'ASTEROID STORM',objective:'Survive the impact window',type:'survive',goal:75,reward:440,time:4500,color:'#ffb347',spawn:['SNIPER','INTERCEPTOR'],effect:'rocks'},
    {id:'BLACKHOLE',name:'BLACK HOLE ANOMALY',objective:'Destroy 10 anomaly guardians',type:'kills',goal:10,reward:520,time:1200,color:'#b56cff',spawn:['HUNTER','ASSASSIN','SNIPER'],effect:'gravity'},
    {id:'SWARM',name:'ALIEN SWARM',objective:'Destroy 25 swarm craft',type:'kills',goal:25,reward:560,time:1200,color:'#7dff6b',spawn:['SWARM','SWARM','INTERCEPTOR'],effect:'swarm'},
    {id:'RESOURCE',name:'RESOURCE RUSH',objective:'Collect 6 war caches',type:'loot',goal:6,reward:700,time:1500,color:'#7dffcc',spawn:['FIGHTER','CARRIER'],effect:'loot'},
    {id:'BOSSHUNT',name:'BOSS HUNT',objective:'Defeat the sector commander',type:'boss',goal:1,reward:850,time:3600,color:'#ff3355',spawn:['ELITE'],effect:'boss'}
  ];
  V.eventDefs=defs;
  const ensure=g=>{g.v9=g.v9||{};if(!g.v9.event)g.v9.event=null;return g.v9};
  function choose(g){const sec=N8.sectorNo(g.level),seed=N8.v9.hash(`${sec}-${Date.now()>>10}`,g.level);const base={...defs[seed%defs.length],progress:0,elapsed:0,active:true,spawned:false,seed};base.baseLoot=V.persist.stats.lootCollected||0;return base};
  function finish(g,success){const e=g.v9?.event;if(!e)return;const v=g.v9;const reward=success?e.reward:0;if(success){g.coins+=reward;V.persist.salvage=(V.persist.salvage||0)+Math.round(reward*.25);V.persist.energyCores=(V.persist.energyCores||0)+Math.max(1,Math.round(reward/300));g.addText(g.canvas.width/2,g.canvas.height*.34,`EVENT COMPLETE · +${reward} CR`,'#5dff8a',1.2);g.toast(`${e.name} COMPLETE`);V.markBattle?.(N8.sectorNo(g.level),'TERRAN',V.owner(N8.sectorNo(g.level)).id,'VICTORY');N8.audio.play('MISSION')}else{g.toast(`${e.name} FAILED`);V.markBattle?.(N8.sectorNo(g.level),V.owner(N8.sectorNo(g.level)).id,'TERRAN','LOSS')}V.setControl?.(N8.sectorNo(g.level),success?'TERRAN':V.owner(N8.sectorNo(g.level)).id,success?8:-5);e.active=false;V.persist.stats.creditsEarned=(V.persist.stats.creditsEarned||0)+reward;N8.v9.saveAll(g)}
  V.events={start:g=>{const v=ensure(g);v.event=choose(g);v.event.startedAt=Date.now();return v.event},finish,defs};
  hook(GameEngine.prototype,'startGame',function(o,...a){const r=o.apply(this,a);ensure(this);if(!this.v9.event)this.v9.event=choose(this);return r});
  hook(GameEngine.prototype,'spawnWave',function(o,...a){const g=this;ensure(g);if(!g.v9.event)g.v9.event=choose(g);const e=g.v9.event;const r=o.apply(this,a);if(!e||e.spawned)return r;e.spawned=true;const count=Math.min(6,e.spawn.length+(e.id==='SWARM'?3:0));for(let i=0;i<count;i++){const role=e.spawn[i%e.spawn.length];g.enemies.push(new Enemy(rnd(50,g.canvas.width-50),-40-i*36,g.level,'STANDARD',role));}if(e.effect==='capital'&&!g.v9.capital){const kind=N8.v9.hash('CAP'+g.level)%2?'CRUISER':'DREADNOUGHT';g.v9.capital=new V.capital.CapitalShip(g,kind);g.toast('CAPITAL SIGNATURE DETECTED')}if(e.effect==='boss'&&!g.boss){g.boss=new Boss(g.canvas.width,g.level);g.toast('COMMANDER SIGNATURE FORCED BY EVENT')}if(e.effect==='escort'||e.effect==='convoy'){g.v9.convoy={x:-80,y:g.canvas.height*.38,hp:900+g.level*8,maxHp:900+g.level*8,vy:-.08,active:true,t:0}}if(e.effect==='rocks'){for(let i=0;i<5;i++){g.v8.rocks=g.v8.rocks||[];g.v8.rocks.push({x:rnd(40,g.canvas.width-40),y:-60-i*70,vx:rnd(-.5,.5),vy:rnd(2,3.5),hp:130+g.level*2,maxHp:130+g.level*2,r:22+Math.random()*12,rot:0,vr:rnd(-.03,.03),img:Math.floor(Math.random()*6)})}}return r});
  N8.pre.push(g=>{const e=g.v9?.event;if(!e||!e.active||g.state!==GAME.PLAYING)return;e.elapsed++;if(g.v9.convoy?.active){const a=g.v9.convoy;a.t++;a.x+=.38+Math.min(1,g.level*.001);a.y=g.canvas.height*.38+Math.sin(a.t*.03)*28;for(const bl of g.bullets){if(!bl.isEnemy||bl.dead)continue;if(Math.hypot(bl.x-a.x,bl.y-a.y)<34){a.hp-=bl.damage;bl.dead=true;g.v8.fx.push({t:'spark',x:bl.x,y:bl.y,n:2})}}if(a.hp<=0){a.active=false;finish(g,false)}}if(e.effect==='gravity'){const dx=g.player.x-g.canvas.width*.5,dy=g.player.y-g.canvas.height*.35;const d=Math.hypot(dx,dy);if(d<260&&g.player.dashTimer<=0)g.player.x+=-dx*.004}if(e.type==='survive')e.progress=Math.floor(e.elapsed/60);if(e.type==='capital')e.progress=g.v9.capital?0:1;if(e.type==='boss')e.progress=g.boss?0:1;if(e.type==='loot')e.progress=Math.min(e.goal,V.persist.stats.lootCollected-(e.baseLoot||0));if(e.progress>=e.goal){finish(g,true)}else if(e.elapsed>=e.time){finish(g,false)}});
  hook(GameEngine.prototype,'killEnemy',function(o,e){const r=o.call(this,e),ev=this.v9?.event;if(ev?.active&&e){if(ev.type==='kills')ev.progress++;if(ev.effect==='swarm'&&e.role!=='SWARM'){}if(ev.type==='loot')ev.progress=Math.min(ev.goal,(V.persist.stats.lootCollected||0)-(ev.baseLoot||0));if(ev.progress>=ev.goal)finish(this,true);}return r});
  hook(GameEngine.prototype,'defeatBoss',function(o,...a){const ev=this.v9?.event;const r=o.apply(this,a);if(ev?.active&&(ev.type==='boss'||ev.effect==='capital')){ev.progress=ev.goal;finish(this,true)}return r});
  N8.resetFns.push(g=>{g.v9=g.v9||{};g.v9.event=null;g.v9.convoy=null});
  N8.addDraw(56,(g,c)=>{const a=g.v9?.convoy;if(!a?.active)return;c.save();c.translate(a.x,a.y);c.fillStyle='#152536';c.strokeStyle='#5ec8ff';c.lineWidth=2;c.beginPath();c.moveTo(-36,-14);c.lineTo(30,-10);c.lineTo(42,0);c.lineTo(30,10);c.lineTo(-36,14);c.closePath();c.fill();c.stroke();c.fillStyle='#5ec8ff';c.fillRect(-23,-5,24,10);c.fillStyle='rgba(0,0,0,.7)';c.fillRect(-36,-24,72,5);c.fillStyle='#5dff8a';c.fillRect(-36,-24,72*Math.max(0,a.hp/a.maxHp),5);c.restore()});
  N8.addDraw(18,(g,c)=>{const e=g.v9?.event;if(!e?.active||g.state!==GAME.PLAYING)return;const W=g.canvas.width;c.save();c.fillStyle='rgba(2,6,14,.72)';c.fillRect(W*.5-220,12,440,44);c.strokeStyle=e.color;c.strokeRect(W*.5-220,12,440,44);c.fillStyle=e.color;c.font='800 10px Orbitron';c.textAlign='center';c.fillText(`${e.name} // ${Math.floor(Math.max(0,(e.time-e.elapsed)/60))}s`,W*.5,28);c.fillStyle='#dce7f3';c.font='600 9px Rajdhani';c.fillText(`${e.objective} · ${Math.min(e.progress,e.goal)} / ${e.goal}`,W*.5,44);c.restore()});
})();

/* v15.1.1 deterministic asset registration */
window.NEBULA_BOOT?.asset('v9-events.js');
