'use strict';
/* NEBULA PROTOCOL v9 — equipment, modules and multi-loadout persistence. */
(()=>{
  const N8=window.N8,V=N8.v9,hook=N8.hook,clamp=N8.clamp,rnd=N8.rnd,$=N8.$;
  const slots=['HULL','ENGINE','SHIELD','REACTOR','WEAPON CORE','ARMOR','COMPUTER','SPECIAL MODULE'];
  const rarities=[
    {id:'COMMON',color:'#cfd8e3',mul:1,cap:1},
    {id:'UNCOMMON',color:'#4dff88',mul:1.15,cap:1.1},
    {id:'RARE',color:'#4d9bff',mul:1.3,cap:1.2},
    {id:'EPIC',color:'#b04dff',mul:1.5,cap:1.35},
    {id:'LEGENDARY',color:'#ffab2e',mul:1.75,cap:1.5},
    {id:'MYTHIC',color:'#ff3d7f',mul:2.0,cap:1.65}
  ];
  const slotBase={
    HULL:['MAX HP',18,'hp'],ENGINE:['SPEED',.18,'speed'],SHIELD:['MAX SHIELD',15,'shield'],REACTOR:['MAX ENERGY',15,'energy'],
    'WEAPON CORE':['DAMAGE',.045,'damage'],ARMOR:['ARMOR',.025,'armor'],COMPUTER:['CRIT',.008,'crit'],'SPECIAL MODULE':['COOLDOWN REDUCTION',.02,'cdr']
  };
  const passivePool={HULL:['ARMOR','SHIELD REGEN'],ENGINE:['EVASION','SPEED'],SHIELD:['SHIELD REGEN','MAX SHIELD'],REACTOR:['ENERGY REGEN','MAX ENERGY'],'WEAPON CORE':['CRITICAL DAMAGE','ARMOR PENETRATION','FIRE RATE'],ARMOR:['ARMOR','HULL REGEN'],COMPUTER:['CRIT','LOOT LUCK','FIRE RATE'],'SPECIAL MODULE':['DASH COOLDOWN','XP GAIN','WEAPON RANGE']};
  const nameA=['AURORA','NEXUS','OBSIDIAN','VANGUARD','ECLIPSE','PHANTOM','HELIX','QUANTUM','SOLAR','VOID','ATLAS','PRISM'];
  const nameB=['CORE','MATRIX','PLATING','DRIVE','ARRAY','CAPACITOR','NODE','LATTICE','WEAVE','REACTOR','CIRCUIT','SIGIL'];
  const st=()=>{V.persist.modules=V.persist.modules||{inventory:[],equipped:{}};V.persist.modules.inventory=Array.isArray(V.persist.modules.inventory)?V.persist.modules.inventory:[];V.persist.modules.equipped=V.persist.modules.equipped||{};return V.persist.modules};
  const ensureStarter=()=>{const m=st();for(const sl of slots)if(!m.equipped[sl]){const found=m.inventory.find(x=>x.slot===sl);m.equipped[sl]=found?found.id:null;}if(m.inventory.length===0){for(const sl of slots)m.inventory.push(make(sl,0,'COMMON'));for(const sl of slots)m.equipped[sl]=m.inventory.find(x=>x.slot===sl)?.id||null;}V.v9equipped=m.equipped;};
  function make(slot,level=1,rarity){const rr=rarity||rarities[Math.min(rarities.length-1,Math.floor(Math.random()*rarities.length))].id;const r=rarities.find(x=>x.id===rr)||rarities[0],base=slotBase[slot],amount=base[1]*r.mul*(1+Math.min(2,level)*.11);const passive=passivePool[slot][(V.hash(Date.now()+slot+Math.random())+level)%passivePool[slot].length];const pval=passive==='LOOT LUCK'?Math.min(.3,.03*r.mul+level*.004):passive==='CRITICAL DAMAGE'?Math.round(6*r.mul+level*1.2):passive==='ARMOR PENETRATION'?Math.min(.25,.025*r.mul+level*.003):passive==='FIRE RATE'?Math.min(.2,.012*r.mul+level*.002):passive==='XP GAIN'?Math.min(.2,.02*r.mul+level*.003):passive==='WEAPON RANGE'?Math.min(.18,.018*r.mul+level*.002):passive==='DASH COOLDOWN'?Math.min(.22,.025*r.mul+level*.002):passive==='SHIELD REGEN'?Math.min(.25,.018*r.mul+level*.002):passive==='ENERGY REGEN'?Math.min(.25,.018*r.mul+level*.002):passive==='HULL REGEN'?Math.min(.2,.018*r.mul+level*.002):passive==='EVASION'?Math.min(.18,.01*r.mul+level*.001):passive==='MAX SHIELD'?Math.round(7*r.mul+level*1.2):passive==='MAX ENERGY'?Math.round(7*r.mul+level*1.2):.01;
    return {id:`M${Date.now().toString(36)}${Math.floor(Math.random()*1e6).toString(36)}`,name:`${nameA[V.hash(slot+rr)%nameA.length]} ${nameB[V.hash(slot+level)%nameB.length]}`,slot,rarity:r.id,level:Math.max(1,level|0),stats:{[base[2]]:Number(amount.toFixed(3))},passive:{id:passive,value:pval},upgrade:0,sell:Math.round(35*r.mul*(level+1)),created:Date.now()};
  }
  V.loot={slots,rarities,make,starter:ensureStarter};
  V.moduleStats=(equipped=st().equipped)=>{const out={speed:0,hp:0,shield:0,energy:0,damage:0,armor:0,crit:0,cdr:0,passive:{}};for(const sl of slots){const it=st().inventory.find(x=>x.id===equipped?.[sl]);if(!it)continue;for(const [k,v] of Object.entries(it.stats||{}))out[{speed:'speed',hp:'hp',shield:'shield',energy:'energy',damage:'damage',armor:'armor',crit:'crit'}[k]||k]=(out[{speed:'speed',hp:'hp',shield:'shield',energy:'energy',damage:'damage',armor:'armor',crit:'crit'}[k]||k]||0)+v;out.passive[it.passive?.id]=(out.passive[it.passive?.id]||0)+(Number(it.passive?.value)||0)}return out};
  V.applyEquipment=(g)=>{if(!g?.player)return;ensureStarter();const p=g.player,s=V.moduleStats();p.v9base=p.v9base||{speed:p.speed,maxHp:p.maxHp,maxShield:p.maxShield,maxEnergy:p.maxEnergy,damage:p.damage,armor:p.armor||0,crit:p.crit||0,fireRate:p.fireRate,cdMul:p.cdMul||1,missileMul:p.missileMul||1};const b=p.v9base;p.speed=b.speed*(1+s.speed)+(s.passive.EVASION>0?1+s.passive.EVASION*.3:1);p.maxHp=b.maxHp+s.hp;p.hp=Math.min(p.maxHp,p.hp+(s.hp||0)*.25);p.maxShield=b.maxShield+s.shield;p.shield=Math.min(p.maxShield,p.shield+(s.shield||0)*.25);p.maxEnergy=b.maxEnergy+s.energy;p.energy=Math.min(p.maxEnergy,p.energy+(s.energy||0)*.25);p.damage=b.damage*(1+s.damage);p.armor=clamp((b.armor||0)+s.armor,0,.65);p.crit=clamp((b.crit||0)+s.crit,0,.75);p.fireRate=Math.max(3,b.fireRate*(1-(s.passive['FIRE RATE']||0)));p.cdMul=Math.max(.45,b.cdMul*(1-Math.min(.25,s.cdr)));p.missileMul=b.missileMul*(1+(s.passive['MISSILE DAMAGE']||0));p.xpMul=1+(s.passive['XP GAIN']||0);p.lootLuck=(b.lootLuck||0)+(s.passive['LOOT LUCK']||0);p.magnet=Math.max(p.magnet||0,70+(g.upgrades?.magnet||1)*8);g.v9EquipmentDirty=false;};
  function awardItem(g,source='COMBAT',force=false){if(st().inventory.length>=80&&!force){g.toast('MODULE BAY FULL — SELL OR UPGRADE GEAR');return null}let tier=Math.min(5,Math.floor((g.level||1)/12));if(source==='BOSS')tier=Math.min(5,tier+1);if(source==='CAPITAL')tier=Math.min(5,tier+1);const r=rarities[Math.min(5,Math.max(0,tier+(Math.random()<.2?1:0)))].id;const item=make(slots[V.hash(source+Date.now())%slots.length],Math.max(1,Math.floor((g.level||1)/10)+1),r);st().inventory.push(item);V.persist.stats.lootCollected=(V.persist.stats.lootCollected||0)+1;N8.v9.write(N8.v9.saveKey,V.persist);g.toast(`${item.rarity} MODULE — ${item.name}`);if(r==='MYTHIC')N8.audio.play('LEVELUP');return item}
  V.dropModule=(g,x,y,source='COMBAT')=>{const v=g.v9;if(!v)return;if(v.itemsWorld.length>=18)return;if(Math.random()>.28&&source==='COMBAT')return;const tier=Math.min(5,Math.floor((g.level||1)/10)+(source==='BOSS'?1:0));const r=rarities[Math.min(5,tier)].id;v.itemsWorld.push({x,y,vx:rnd(-1,.1),vy:rnd(-.8,.2),life:900,item:make(slots[V.hash(x+y+source)%slots.length],Math.max(1,Math.floor((g.level||1)/9)+1),r)});};
  N8.resetFns.push(g=>{g.v9=g.v9||{};g.v9.itemsWorld=[];g.v9EquipmentDirty=true;ensureStarter();});
  hook(GameEngine.prototype,'startGame',function(o,...a){const r=o.apply(this,a);this.v9=this.v9||{};this.v9.itemsWorld=[];V.applyEquipment(this);return r});
  hook(GameEngine.prototype,'selectShip',function(o,id){const r=o.call(this,id);if(this.state!==GAME.PLAYING)this.v9EquipmentDirty=true;return r});
  hook(GameEngine.prototype,'killEnemy',function(o,e){const r=o.call(this,e);if(!e?.v9ModuleAward&&!e?.deadModule){e.v9ModuleAward=1;V.dropModule(this,e.x,e.y,e.type==='ELITE'?'ELITE':'COMBAT')}return r});
  hook(GameEngine.prototype,'defeatBoss',function(o,...a){const r=o.apply(this,a);V.dropModule(this,this.canvas.width/2,this.canvas.height*.35,'BOSS');awardItem(this,'BOSS',true);return r});
  N8.pre.push(g=>{if(!g.player||!g.v9)return;if(g.v9EquipmentDirty) V.applyEquipment(g);const arr=g.v9.itemsWorld;for(let i=arr.length-1;i>=0;i--){const it=arr[i];it.life--;it.vx*=.98;it.vy+=.03;const d=Math.hypot(g.player.x-it.x,g.player.y-it.y);if(d<85){const f=(1-d/85)*4;it.x+=(g.player.x-it.x)/(d||1)*f;it.y+=(g.player.y-it.y)/(d||1)*f}else{it.x+=it.vx;it.y+=it.vy}if(d<28){const m=st();if(m.inventory.length<80){m.inventory.push(it.item);V.persist.stats.lootCollected=(V.persist.stats.lootCollected||0)+1;g.toast(`${it.item.rarity} MODULE ACQUIRED`);if(it.item.rarity==='MYTHIC')N8.achievement?.unlock(g,'MYTHIC_DROP');}arr.splice(i,1);N8.v9.saveAll(g)}else if(it.life<=0)arr.splice(i,1)}});
  N8.addDraw(35,(g,c)=>{for(const it of g.v9?.itemsWorld||[]){const r=rarities.find(x=>x.id===it.item.rarity)||rarities[0];c.save();c.translate(it.x,it.y);c.globalCompositeOperation='lighter';c.strokeStyle=r.color;c.globalAlpha=.65+.25*Math.sin((g.v8?.t||0)*.15+it.x);c.beginPath();c.arc(0,0,9,0,7);c.stroke();c.globalCompositeOperation='source-over';c.globalAlpha=1;c.fillStyle=r.color;c.font='800 7px Orbitron';c.textAlign='center';c.fillText(it.item.slot[0],0,2);c.restore()}});
  /* Module upgrade and selling are used by v9 UI. */
  V.upgradeModule=(g,id)=>{const m=st().inventory.find(x=>x.id===id);if(!m||m.upgrade>=5){g?.toast('MODULE AT MAX LEVEL');return false}const cost=45+m.level*28+m.upgrade*55;if((V.persist.salvage||0)<cost){g?.toast('NOT ENOUGH SALVAGE');return false}V.persist.salvage-=cost;m.upgrade++;m.level++;for(const k in m.stats)m.stats[k]=Number((m.stats[k]*1.08).toFixed(3));m.sell=Math.round(m.sell*1.08);V.persist.stats.creditsEarned=(V.persist.stats.creditsEarned||0);N8.v9.write(N8.v9.saveKey,V.persist);g?.toast(`${m.name} UPGRADED`);return true};
  V.sellModule=(g,id)=>{const m=st().inventory.find(x=>x.id===id);if(!m)return false;if(Object.values(st().equipped).includes(id)){g.toast('UNEQUIP MODULE BEFORE SELLING');return false}g.coins+=m.sell;st().inventory=st().inventory.filter(x=>x.id!==id);N8.v9.saveAll(g);g.toast(`MODULE SOLD +${m.sell} CR`);return true};
  V.saveLoadout=(g,slot)=>{V.persist.loadouts=V.persist.loadouts||{};V.persist.loadouts[String(slot)]={ship:g.selectedShip,loadout:JSON.parse(JSON.stringify(N8.loadout)),equipped:JSON.parse(JSON.stringify(st().equipped)),customization:JSON.parse(JSON.stringify(V.persist.customization||{}))};N8.v9.saveAll(g);};
  V.activateLoadout=(g,slot)=>{const l=V.persist.loadouts?.[String(slot)];if(!l)return false;const ship=l.ship;if(ship&&g.unlockedShips.includes(ship))g.selectedShip=ship;if(l.loadout)Object.assign(N8.loadout,JSON.parse(JSON.stringify(l.loadout)));if(l.equipped)st().equipped=JSON.parse(JSON.stringify(l.equipped));if(l.customization)V.persist.customization=Object.assign(V.persist.customization||{},l.customization);N8.saveLoadout?.();g.renderShips?.();N8.v9.saveAll(g);g.toast(`LOADOUT ${slot} ACTIVATED`);return true};
})();

/* v15.1.1 deterministic asset registration */
window.NEBULA_BOOT?.asset('v9-loot.js');
