'use strict';
/* NEBULA PROTOCOL v9 — responsive command UI. All controls call live game systems. */
(()=>{
  const N8=window.N8,V=N8.v9,$=N8.$,hook=N8.hook,clamp=N8.clamp;
  const G=()=>window.gameEngine;
  const hideIds=['mainMenu','upgradeMenu','levelSelectMenu','missionsMenu','codexMenu','settingsMenu','v9Map','v9War','v9Command','gameOverMenu'];
  const hideAll=()=>hideIds.forEach(id=>$(id)?.classList.add('hidden'));
  const show=id=>{hideAll();$(id)?.classList.remove('hidden')};
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  function btn(t,a,d=''){return `<button class="v9-btn" data-v9="${a}" ${d}>${t}</button>`}
  function ensureRoot(){
    if($('v9Root'))return;
    const ui=$('uiContainer');if(!ui)return;
    const root=document.createElement('div');root.id='v9Root';root.innerHTML=`
      <div class="v9-version">ASCENSION v10 · GALACTIC WAR</div>
      <section id="v9Map" class="screen cyber-panel wide hidden v9-screen"><div class="v9-head"><div><div class="eyebrow">STRATEGIC COMMAND // GALACTIC MAP</div><h2>GALACTIC MAP</h2></div><div class="v9-head-actions">${btn('WARFRONT','war')}${btn('COMMAND DECK','command')}${btn('RETURN','menu')}</div></div><div class="v9-map-layout"><canvas id="v9MapCanvas" width="1000" height="680" aria-label="Interactive galactic map"></canvas><aside id="v9SectorInfo" class="v9-side"></aside></div></section>
      <section id="v9War" class="screen cyber-panel wide hidden v9-screen"><div class="v9-head"><div><div class="eyebrow">WAR NETWORK // LIVE LOCAL SIMULATION</div><h2>WARFRONT STATUS</h2></div><div>${btn('GALAXY','map')}${btn('COMMAND DECK','command')}${btn('RETURN','menu')}</div></div><div id="v9WarBody" class="v9-grid-layout"></div></section>
      <section id="v9Command" class="screen cyber-panel wide hidden v9-screen"><div class="v9-head"><div><div class="eyebrow">TACTICAL OPERATIONS</div><h2>COMMAND DECK</h2></div><div>${btn('GALAXY','map')}${btn('WARFRONT','war')}${btn('RETURN','menu')}</div></div><div class="v9-tabs"><button class="v9-tab active" data-v9tab="campaign">CAMPAIGN</button><button class="v9-tab" data-v9tab="contracts">CONTRACTS</button><button class="v9-tab" data-v9tab="daily">DAILY</button><button class="v9-tab" data-v9tab="achievements">ACHIEVEMENTS</button><button class="v9-tab" data-v9tab="stats">STATISTICS</button><button class="v9-tab" data-v9tab="modules">MODULES</button><button class="v9-tab" data-v9tab="loadouts">LOADOUTS</button><button class="v9-tab" data-v9tab="customization">CUSTOMIZE</button></div><div id="v9CommandBody" class="v9-command-body"></div></section>
      <section id="v9Debug" class="v9-modal hidden"><div class="v9-debug-card"><div class="v9-head"><div><div class="eyebrow">DEVELOPER CHANNEL // HIDDEN</div><h3>V10 DEBUG CONSOLE</h3></div>${btn('CLOSE','debug-close')}</div><div id="v9DebugBody"></div></div></section>
      <div id="v9HudEvent" class="v9-hud-event" aria-live="polite">WARFRONT ONLINE</div><div id="v9Touch" class="v9-touch hidden" aria-label="Mobile tactical controls"><button data-touch="dash">DASH</button><button data-touch="lock">LOCK</button><button data-touch="special">SPECIAL</button><button data-touch="fire">FIRE</button></div>`;
    ui.appendChild(root);
    bind(root);buildMenuLinks();buildSettings();
    window.addEventListener('resize',()=>resizeMapCanvas());
  }
  function buildMenuLinks(){
    const host=$('mainMenu')?.querySelector('.menu-actions');if(!host||host.querySelector('.v9-menu-row'))return;const row=document.createElement('div');row.className='v9-menu-row';row.innerHTML=`${btn('GALACTIC MAP','map')} ${btn('WARFRONT','war')} ${btn('COMMAND DECK','command')}`;host.appendChild(row);
    const hang=$('upgradeMenu');if(hang&&!hang.querySelector('.v9-hangar-tools')){const d=document.createElement('div');d.className='v9-hangar-tools';d.innerHTML=`<span class="v9-chip">MODULES</span>${btn('COMMAND DECK','command')} ${btn('CUSTOMIZE','customization')} ${btn('LOADOUTS','loadouts')}`;hang.insertBefore(d,hang.querySelector('.tabs'));}
  }
  function buildSettings(){
    const list=$('settingsMenu')?.querySelector('.settings-list');if(!list||list.querySelector('.v9-settings'))return;const div=document.createElement('div');div.className='v9-settings';div.innerHTML=`<label><span>REDUCED MOTION</span><input id="v9ReducedMotion" type="checkbox"></label><label><span>HIGH CONTRAST</span><input id="v9HighContrast" type="checkbox"></label><label><span>SIMPLIFIED HUD</span><input id="v9SimpleHud" type="checkbox"></label><label><span>UI SCALE</span><select id="v9UiScale"><option value=".9">90%</option><option value="1">100%</option><option value="1.1">110%</option><option value="1.2">120%</option></select></label><label><span>TOUCH LAYOUT</span><select id="v9TouchHand"><option value="right">RIGHT HANDED</option><option value="left">LEFT HANDED</option></select></label><div class="v9-audio"><b>AUDIO MIX</b><label>MASTER <input id="v9VolMaster" type="range" min="0" max="1" step=".05"></label><label>MUSIC <input id="v9VolMusic" type="range" min="0" max="1" step=".05"></label><label>WEAPONS <input id="v9VolWeapons" type="range" min="0" max="1" step=".05"></label><label>EXPLOSIONS <input id="v9VolExplosions" type="range" min="0" max="1" step=".05"></label><label>UI/ALERTS <input id="v9VolUI" type="range" min="0" max="1" step=".05"></label></div><div class="v9-save-actions">${btn('EXPORT SAVE','export')}${btn('IMPORT SAVE','import')}${btn('RESET V9 SAVE','reset-v9')}</div>`;list.appendChild(div);syncSettings();
  }
  function syncSettings(){const s=Object.assign({reducedMotion:false,highContrast:false,simplifiedHUD:false,uiScale:1,touchHand:'right',volumeMaster:1,volumeMusic:.45,volumeWeapons:1,volumeExplosions:1,volumeUI:1},V.persist.settings||{});V.persist.settings=s;for(const [id,val] of [['v9ReducedMotion',s.reducedMotion],['v9HighContrast',s.highContrast],['v9SimpleHud',s.simplifiedHUD]]){const e=$(id);if(e)e.checked=!!val}for(const [id,val] of [['v9UiScale',s.uiScale],['v9TouchHand',s.touchHand],['v9VolMaster',s.volumeMaster],['v9VolMusic',s.volumeMusic],['v9VolWeapons',s.volumeWeapons],['v9VolExplosions',s.volumeExplosions],['v9VolUI',s.volumeUI]]){const e=$(id);if(e)e.value=val}applySettings(s)}
  function applySettings(s){const r=document.documentElement;r.style.setProperty('--v9-ui-scale',String(s.uiScale||1));document.body.classList.toggle('v9-contrast',!!s.highContrast);document.body.classList.toggle('v9-simple-hud',!!s.simplifiedHUD);document.body.classList.toggle('v9-reduced-motion',!!s.reducedMotion);$('v9Touch')?.classList.toggle('left',s.touchHand==='left');if(G()?.audio)G().audio.master=.20*Number(s.volumeMaster??1);V.audio?.syncMusic(G())}
  function resizeMapCanvas(){const c=$('v9MapCanvas');if(!c)return;const r=c.getBoundingClientRect(),d=Math.min(window.devicePixelRatio||1,1.5),w=Math.max(640,Math.round(r.width*d)),h=Math.max(480,Math.round(r.height*d));if(c.width!==w||c.height!==h){c.width=w;c.height=h;renderMap()}}
  function renderMap(){const c=$('v9MapCanvas');if(!c)return;const W=c.width,H=c.height,ctx=c.getContext('2d');if(!ctx)return;mapDrawOverlay();renderSectorInfo();}
  function mapDrawOverlay(){const c=$('v9MapCanvas');if(!c)return;const ctx=c.getContext('2d'),W=c.width,H=c.height;const grd=ctx.createRadialGradient(W*.5,H*.5,0,W*.5,H*.5,Math.max(W,H)*.65);grd.addColorStop(0,'#07172c');grd.addColorStop(1,'#01040b');ctx.fillStyle=grd;ctx.fillRect(0,0,W,H);ctx.save();ctx.translate(W*.5+V.galaxy.panX,H*.5+V.galaxy.panY);ctx.scale(V.galaxy.zoom,V.galaxy.zoom);ctx.globalAlpha=.18;for(let i=0;i<65;i++){const x=((V.hash('sx'+i)%1600)-800),y=((V.hash('sy'+i)%1100)-550);ctx.fillStyle=i%3?'#8fb4d9':'#ffffff';ctx.fillRect(x,y,1.2/V.galaxy.zoom,1.2/V.galaxy.zoom)}for(const s of V.visibleSectors()){const rr=(s.id===V.galaxy.selected?9:4)/V.galaxy.zoom;const col=s.status==='LOCKED'?'#314153':s.owner.color;ctx.globalAlpha=s.status==='LOCKED'?.28:.9;ctx.fillStyle=col;ctx.beginPath();ctx.arc(s.x,s.y,rr,0,7);ctx.fill();if(s.boss){ctx.globalAlpha=.8;ctx.strokeStyle='#ff3355';ctx.lineWidth=1.5/V.galaxy.zoom;ctx.beginPath();ctx.arc(s.x,s.y,rr+4/V.galaxy.zoom,0,7);ctx.stroke()}if(s.event){ctx.setLineDash([3,4]);ctx.strokeStyle='#ffe066';ctx.beginPath();ctx.arc(s.x,s.y,rr+7/V.galaxy.zoom,0,7);ctx.stroke();ctx.setLineDash([])}if(s.resource){ctx.globalAlpha=.9;ctx.fillStyle='#7dffcc';ctx.fillRect(s.x-2/V.galaxy.zoom,s.y-12/V.galaxy.zoom,4/V.galaxy.zoom,6/V.galaxy.zoom)}}const ss=V.sector(V.galaxy.selected);ctx.globalAlpha=1;ctx.strokeStyle='#ffffff';ctx.lineWidth=2/V.galaxy.zoom;ctx.beginPath();ctx.arc(ss.x,ss.y,16/V.galaxy.zoom,0,7);ctx.stroke();ctx.fillStyle='#cfe3f5';ctx.font='800 12px Orbitron';ctx.textAlign='center';ctx.fillText(`S${String(ss.id).padStart(3,'0')}`,ss.x,ss.y-20/V.galaxy.zoom);ctx.restore();ctx.fillStyle='#9db4c9';ctx.font='600 11px Rajdhani';ctx.fillText('WHEEL / PINCH = ZOOM · DRAG = PAN · TAP = SELECT',16,H-16)}
  const oldMapDraw=N8._v9OriginalMapDraw; if(!oldMapDraw){N8._v9OriginalMapDraw=true;N8.addDraw(5,(g,c)=>{if(V.mapOpen){/* gameplay renderer bypass: menu map uses its own canvas */}})}
  function renderSectorInfo(){const e=$('v9SectorInfo'),s=V.sector(V.galaxy.selected),g=G();if(!e||!s)return;const unlocked=s.status!=='LOCKED';const lvl=(s.id-1)*10+1;const progress=Math.round(s.control);e.innerHTML=`<div class="v9-card"><span class="v9-kicker">SECTOR ${String(s.id).padStart(3,'0')}</span><h3>${esc(s.name)}</h3><div class="v9-owner" style="--f:${s.owner.color}">${s.owner.emblem} · ${s.owner.name}</div><div class="v9-statgrid"><span>THREAT</span><b>${s.threat}/10</b><span>BOSS</span><b>${s.boss?'COMMANDER':'NONE'}</b><span>STATUS</span><b>${s.status}</b><span>OBJECTIVE</span><b>${s.objective}</b><span>CONTROL</span><b>${progress}%</b><span>REWARD</span><b>${s.reward.toLocaleString()} CR</b><span>EVENT</span><b>${s.event?'SPECIAL':'STANDARD'}</b><span>RESOURCES</span><b>${s.resource?'RICH':'NORMAL'}</b></div><div class="v9-bar"><i style="width:${progress}%"></i></div>${unlocked?btn('LAUNCH SECTOR','launch-sector'):`<div class="v9-locked">LOCKED · START ACCESS: SECTOR ${N8.maxStartSector(g)}</div>`}</div><div class="v9-map-legend"><span><i class="dot terran"></i>FRIENDLY SIMULATION</span><span><i class="dot boss"></i>BOSS</span><span><i class="dot event"></i>EVENT</span><span><i class="dot lock"></i>LOCKED</span></div>`;}
  function renderWar(){const b=$('v9WarBody');if(!b)return;const counts={};for(let i=1;i<=V.galaxy.count;i++){const f=V.owner(i).id;counts[f]=(counts[f]||0)+1}const ev=G()?.v9?.event;let h=`<div class="v9-card v9-war-hero"><div><span class="v9-kicker">WARFRONT STATUS</span><h3>THE GALACTIC FRONT</h3><p>${ev?`ACTIVE EVENT · ${esc(ev.name)} · ${Math.max(0,Math.floor((ev.time-ev.elapsed)/60))}s remaining`:'No global event currently active. Local sector simulation continues.'}</p></div><div class="v9-resource-strip"><b>${(V.persist.credits||G()?.coins||0).toLocaleString()}<small>CR</small></b><b>${V.persist.salvage||0}<small>SALVAGE</small></b><b>${V.persist.tech||0}<small>TECH</small></b><b>${V.persist.energyCores||0}<small>CORES</small></b></div></div><div class="v9-faction-grid">`;for(const f of V.factions){h+=`<article class="v9-faction" style="--f:${f.color}"><div class="v9-faction-mark">${f.emblem}</div><b>${f.name}</b><span>${counts[f.id]||0} sectors · ${f.style}</span><div class="v9-bar"><i style="width:${Math.min(100,Math.round((counts[f.id]||0)/20*100))}%"></i></div><small>TECH ${f.tech} · STRENGTH ${f.strength} · WEAKNESS ${f.weakness}</small></article>`}h+='</div><div class="v9-grid-2"><article class="v9-card"><h3>RECENT BATTLES</h3>';for(const r of (V.persist.galaxy.recentBattles||[]).slice(0,8)){h+=`<div class="v9-log">SECTOR ${String(r.sector).padStart(3,'0')} · ${esc(r.outcome)} · ${esc(V.faction(r.attacker).name)} vs ${esc(V.faction(r.defender).name)}</div>`}h+='</article><article class="v9-card"><h3>ACTIVE THEATRES</h3>';const active=[];for(let i=1;i<=V.galaxy.count;i++){const s=V.sector(i);if((s.event||s.boss||s.resource)&&s.status!=='LOCKED')active.push(s)}for(const s of active.slice(0,10))h+=`<button class="v9-list-btn" data-v9-sector="${s.id}">S${String(s.id).padStart(3,'0')} · ${esc(s.name)} · ${s.boss?'BOSS ':''}${s.event?'EVENT ':''}${s.resource?'RESOURCE':''}</button>`;h+='</article></div>';b.innerHTML=h;}
  function renderCommand(tab='campaign'){const body=$('v9CommandBody');if(!body)return;document.querySelectorAll('.v9-tab').forEach(x=>x.classList.toggle('active',x.dataset.v9tab===tab));const g=G();let h='';
    if(tab==='campaign'){V.campaignSync?.();const c=V.campaign||{};h=`<div class="v9-card v9-campaign"><span class="v9-rarity">ASCENSION CAMPAIGN · CHAPTER ${Number(c.chapter)||1} / 12</span><h3>${esc(c.title||'FRONTIER AWAKENING')}</h3><p>${esc(c.briefing||'Persistent campaign progression follows your sector victories.')}</p><div class="v9-kpi-row"><b>CHAPTERS CLEARED <em>${Number(c.completed)||0}</em></b><b>HIGHEST SECTOR <em>${Number(V.persist.stats.highestSector)||1}</em></b><b>ACTIVE OWNER <em>${esc(V.owner(N8.sectorNo(V.persist.stats.highestSector||1)).name)}</em></b></div></div><div class="v9-card"><h3>WAR DIRECTIVE</h3><p>Campaign chapters are driven by actual sector completion, warfront control, contracts and commander encounters. Progress is stored locally and is not server-synchronized.</p></div>`;} else 
    if(tab==='contracts'){const cs=V.contracts.ensure(g);h='<div class="v9-card-grid">'+cs.map(c=>`<article class="v9-card"><span class="v9-kicker">${esc(c.category)}</span><h3>${esc(c.name)}</h3><p>${esc(c.desc)}</p><div class="v9-progress-line"><i style="width:${Math.min(100,c.progress/c.goal*100)}%"></i></div><b>${Math.floor(c.progress*100)/100} / ${c.goal} · +${c.reward} CR</b></article>`).join('')+'</div>';
    } else if(tab==='daily'){const ds=V.daily.ensure();h='<div class="v9-card-grid">'+ds.map(d=>`<article class="v9-card ${d.done?'done':''}"><span class="v9-kicker">LOCAL DAILY · ${esc(V.daily.today())}</span><h3>${esc(d.name)}</h3><p>${esc(d.desc)}</p><div class="v9-progress-line"><i style="width:${Math.min(100,d.progress/d.goal*100)}%"></i></div><b>${d.progress} / ${d.goal}</b><small>REWARD ${d.reward} CR</small></article>`).join('')+'</div><p class="v9-note">Daily challenges are generated deterministically from this device date. No server synchronization is claimed.</p>';
    } else if(tab==='achievements'){const as=N8.achievement.inspect(g);h='<div class="v9-card-grid">'+as.map(a=>`<article class="v9-card ${a.state.done?'done':''}"><span class="v9-kicker">${a.state.done?'UNLOCKED':'TRACKING'}</span><h3>${esc(a.name)}</h3><p>${esc(a.desc)}</p><div class="v9-progress-line"><i style="width:${Math.min(100,a.state.progress/a.goal*100)}%"></i></div><b>${a.state.progress} / ${a.goal}</b><small>REWARD ${a.reward} CR</small></article>`).join('')+'</div>';
    } else if(tab==='stats'){const s=V.persist.stats,acc=s.shotsFired?((s.shotsHit||0)/s.shotsFired*100):0;h=`<div class="v9-statboard">${[['TOTAL KILLS',s.kills],['BOSS KILLS',s.bossKills],['CAPITAL SHIPS',s.capitalKills],['SHOTS FIRED',s.shotsFired],['SHOTS HIT',s.shotsHit||0],['ACCURACY',acc.toFixed(1)+'%'],['DAMAGE DEALT',Math.round(s.damageDealt||0)],['DAMAGE RECEIVED',Math.round(s.damageReceived||0)],['SECTORS',s.sectorsCompleted],['MISSIONS',s.missionsCompleted],['CREDITS EARNED',Math.round(s.creditsEarned||0)],['LOOT COLLECTED',s.lootCollected||0],['HIGHEST COMBO',(s.highestCombo||1).toFixed(1)],['HIGHEST STREAK',s.highestStreak||0],['PERFECT SECTORS',s.perfectSectors||0],['PLAY TIME',Math.floor((s.playTime||0)/60)+' min'],['FAVORITE SHIP',s.favoriteShip||'-'],['FAVORITE WEAPON',s.favoriteWeapon||'-'],['FAVORITE POWER',s.favoritePower||'-'],['HIGHEST SECTOR',s.highestSector||1]].map(x=>`<div class="v9-statbox"><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('')}</div>`;
    } else if(tab==='modules'){N8.v9.loot.starter();const inv=V.persist.modules.inventory||[];h=`<div class="v9-eq-head"><div class="v9-chip">EQUIPPED</div>${N8.v9.loot.slots.map(sl=>`<span>${sl}: <b>${esc(inv.find(x=>x.id===V.persist.modules.equipped[sl])?.name||'EMPTY')}</b></span>`).join('')}</div><div class="v9-module-grid">${inv.map(m=>{const r=N8.v9.loot.rarities.find(x=>x.id===m.rarity)||N8.v9.loot.rarities[0],eq=V.persist.modules.equipped[m.slot]===m.id;return `<article class="v9-module" data-module-id="${esc(m.id)}" style="--r:${r.color}"><span class="v9-rarity">${m.rarity} · LV ${m.level}</span><h3>${esc(m.name)}</h3><small>${esc(m.slot)}</small><p>${Object.entries(m.stats||{}).map(x=>`${x[0]} +${x[1]}`).join(' · ')}</p><p>PASSIVE · ${esc(m.passive?.id||'-')} ${Number(m.passive?.value||0).toFixed(2)}</p><div>${eq?'<b class="v9-equipped">EQUIPPED</b>':''}${btn(eq?'EQUIPPED':'EQUIP','equip-module',eq?'disabled':'')} ${btn('UPGRADE','upgrade-module')} ${btn('SELL','sell-module')}</div></article>`}).join('')}</div>`;
    } else if(tab==='loadouts'){h=`<div class="v9-loadout-grid">${[1,2,3,4,5].map(i=>{const l=V.persist.loadouts?.[String(i)],name=l?.name||`LOADOUT ${i}`;return `<article class="v9-card"><span class="v9-kicker">SLOT ${i}</span><h3>${esc(name)}</h3><p>${l?`${esc(l.ship)} · ${esc(N8.W[l.loadout?.primary||0]?.n||'PRIMARY')} · ${esc(N8.MISSILES[l.loadout?.missile||'HOMING']?.n||'MISSILE')}`:'EMPTY SLOT'}</p>${btn(l?'ACTIVATE':'SAVE CURRENT',l?'activate-loadout':'save-loadout')}${l?` ${btn('OVERWRITE','save-loadout')}`:''}</article>`}).join('')}</div>`;
    } else {const c=V.customization.get();h=`<div class="v9-custom-grid"><article class="v9-card"><h3>PAINT / ENERGY</h3><label>PRIMARY <input id="v9Primary" type="color" value="${c.primary}"></label><label>SECONDARY <input id="v9Secondary" type="color" value="${c.secondary}"></label><label>ENGINE <input id="v9Engine" type="color" value="${c.engine}"></label><label>SHIELD <input id="v9Shield" type="color" value="${c.shield}"></label><label>EMBLEM <input id="v9Emblem" maxlength="3" value="${esc(c.emblem)}"></label><label>FINISH <select id="v9Finish"><option>SATIN</option><option>MATTE</option><option>POLISHED</option><option>FIELD</option></select></label><label>TRAIL <select id="v9Trail"><option>ION</option><option>PLASMA</option><option>PULSE</option><option>VOID</option></select></label>${btn('APPLY CUSTOMIZATION','apply-custom')}</article><article class="v9-card v9-preview"><h3>LIVE PROFILE</h3><div class="v9-emblem" style="--f:${c.primary}">${esc(c.emblem||'N')}</div><p>Customization is persistent and applied to the live player ship presentation on the next launch.</p></article></div>`;}
    body.innerHTML=h;const fin=$('v9Finish');if(fin)fin.value=V.customization.get().finish;const tr=$('v9Trail');if(tr)tr.value=V.customization.get().trail;
  }
  function bind(root){
    root.addEventListener('click',e=>{const b=e.target.closest('[data-v9]');if(!b||b.disabled)return;const a=b.dataset.v9,g=G();if(a==='menu'){V.mapOpen=false;show('mainMenu');g?.updateMenu();return}if(a==='map'){V.openMap();show('v9Map');resizeMapCanvas();renderMap();return}if(a==='war'){show('v9War');renderWar();return}if(a==='command'){show('v9Command');renderCommand('campaign');return}if(a==='debug-close'){$('v9Debug').classList.add('hidden');return}if(a==='launch-sector'){const s=V.sector(V.galaxy.selected),lv=(s.id-1)*10+1;V.mapOpen=false;hideAll();g?.startGame(lv,'SELECTED');return}if(a==='export'){const raw=N8.v9.exportString(g);const blob=new Blob([raw],{type:'application/json'});const url=URL.createObjectURL(blob);const ael=document.createElement('a');ael.href=url;ael.download='nebula9-save.json';ael.click();URL.revokeObjectURL(url);g?.toast('V9 SAVE EXPORTED');return}if(a==='import'){const inp=document.createElement('input');inp.type='file';inp.accept='.json,application/json';inp.onchange=()=>{const f=inp.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{N8.v9.importString(g,String(r.result||''));location.reload()}catch(err){g?.toast('IMPORT FAILED: INVALID SAVE')}};r.readAsText(f)};inp.click();return}if(a==='reset-v9'){if(confirm('Reset the v9 save layer and v9 progress? Existing v8 keys are retained until a full reset.')){N8.v9.reset();location.reload()}return}if(a==='customization'){show('v9Command');renderCommand('customization');return}if(a==='loadouts'){show('v9Command');renderCommand('loadouts');return}if(a==='save-loadout'){const slot=[...root.querySelectorAll('.v9-loadout-grid .v9-card')].indexOf(b.closest('.v9-card'))+1;V.loot.saveLoadout(g,slot);renderCommand('loadouts');return}if(a==='activate-loadout'){const slot=[...root.querySelectorAll('.v9-loadout-grid .v9-card')].indexOf(b.closest('.v9-card'))+1;V.loot.activateLoadout(g,slot);renderCommand('loadouts');return}if(a==='equip-module'){const id=b.closest('.v9-module')?.dataset.moduleId;if(id){const m=V.persist.modules.inventory.find(x=>x.id===id);V.persist.modules.equipped[m.slot]=m.id;g.v9EquipmentDirty=true;N8.v9.saveAll(g);renderCommand('modules')}}if(a==='upgrade-module'){const id=b.closest('.v9-module')?.dataset.moduleId;const m=V.persist.modules.inventory.find(x=>x.id===id);if(m)V.loot.upgradeModule(g,m.id);renderCommand('modules')}if(a==='sell-module'){const id=b.closest('.v9-module')?.dataset.moduleId;const m=V.persist.modules.inventory.find(x=>x.id===id);if(m)V.loot.sellModule(g,m.id);renderCommand('modules')}});
    root.addEventListener('click',e=>{const b=e.target.closest('[data-v9-sector]');if(!b)return;V.galaxy.selected=Number(b.dataset.v9Sector)||1;show('v9Map');resizeMapCanvas();renderMap();});
    root.querySelectorAll('.v9-tab').forEach(b=>b.addEventListener('click',()=>renderCommand(b.dataset.v9tab)));
    root.addEventListener('change',e=>{const id=e.target.id,s=V.persist.settings||{};const map={v9ReducedMotion:'reducedMotion',v9HighContrast:'highContrast',v9SimpleHud:'simplifiedHUD',v9UiScale:'uiScale',v9TouchHand:'touchHand',v9VolMaster:'volumeMaster',v9VolMusic:'volumeMusic',v9VolWeapons:'volumeWeapons',v9VolExplosions:'volumeExplosions',v9VolUI:'volumeUI'};if(map[id]){s[map[id]]=e.target.type==='checkbox'?e.target.checked:(id==='v9UiScale'?Number(e.target.value):e.target.value);V.persist.settings=s;applySettings(s);N8.v9.saveAll(G())} });
    root.addEventListener('click',e=>{const t=e.target.closest('[data-touch]');if(!t)return;e.preventDefault();e.stopPropagation();const g=G();const a=t.dataset.touch;if(a==='dash')g?.dash();if(a==='lock')g?.lockNearest();if(a==='special')g?.useSpecial()},{capture:true});
    for(const t of root.querySelectorAll('[data-touch]')){const start=ev=>{ev.preventDefault();ev.stopPropagation();const g=G();if(t.dataset.touch==='fire'){if(g?.state===GAME.PLAYING){g.audio.init();g.pointerFire=true}}};const end=ev=>{ev.preventDefault();ev.stopPropagation();if(t.dataset.touch==='fire'&&G())G().pointerFire=false};t.addEventListener('pointerdown',start);t.addEventListener('pointerup',end);t.addEventListener('pointercancel',end);t.addEventListener('pointerleave',end)}
    const mc=$('v9MapCanvas');if(mc){let drag=null,points=new Map(),pinchStart=0,pinchZoom=1;const dist=()=>{const a=[...points.values()];return a.length<2?0:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y)};mc.addEventListener('pointerdown',e=>{points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.size===1)drag={x:e.clientX,y:e.clientY,px:V.galaxy.panX,py:V.galaxy.panY};else if(points.size===2){pinchStart=dist();pinchZoom=V.galaxy.zoom}mc.setPointerCapture?.(e.pointerId)});mc.addEventListener('pointermove',e=>{if(points.has(e.pointerId))points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(points.size===2&&pinchStart){const q=dist();if(q>2)V.galaxy.zoom=clamp(pinchZoom*(q/pinchStart),.55,2.3);renderMap()}else if(drag&&points.size===1){V.galaxy.panX=drag.px+(e.clientX-drag.x);V.galaxy.panY=drag.py+(e.clientY-drag.y);renderMap()}});mc.addEventListener('pointerup',e=>{const q=points.size;points.delete(e.pointerId);if(q>=2){pinchStart=0;drag=null;return}if(!drag)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.hypot(dx,dy)<8){const r=mc.getBoundingClientRect(),x=(e.clientX-r.left)*(mc.width/(r.width||1)),y=(e.clientY-r.top)*(mc.height/(r.height||1));let best=null,bd=1e9;for(const ss of V.visibleSectors()){const sx=mc.width/2+V.galaxy.panX+ss.x*V.galaxy.zoom,sy=mc.height/2+V.galaxy.panY+ss.y*V.galaxy.zoom,d=Math.hypot(x-sx,y-sy);if(d<bd){bd=d;best=ss}}if(best&&bd<32){V.galaxy.selected=best.id;renderMap()}}drag=null});mc.addEventListener('pointercancel',e=>{points.delete(e.pointerId);drag=null;pinchStart=0});mc.addEventListener('wheel',e=>{e.preventDefault();V.galaxy.zoom=clamp(V.galaxy.zoom*(e.deltaY<0?1.12:.89),.55,2.3);renderMap()},{passive:false})}
  }
  function v9TouchVisibility(){const showMobile=window.matchMedia?.('(pointer:coarse)').matches||window.innerWidth<900;$('v9Touch')?.classList.toggle('hidden',!showMobile||G()?.state!==GAME.PLAYING);}
  function debugOpen(){ensureRoot();$('v9Debug').classList.remove('hidden');renderDebug();}
  function renderDebug(){const g=G(),p=g?.player,v=g?.v8,b=g?.v9?.capital,body=$('v9DebugBody');if(!body)return;body.innerHTML=`<div class="v9-debug-grid">${[['FPS',g?.v9Perf?.fps||60],['FRAME TIME',(g?.v9Perf?.frameMs||16.7).toFixed(1)+'ms'],['ENTITIES',(g?.enemies?.length||0)+(g?.bullets?.length||0)+(g?.particles?.length||0)],['ENEMIES',g?.enemies?.length||0],['BULLETS',g?.bullets?.length||0],['PARTICLES',g?.particles?.length||0],['SECTOR',N8.sectorNo(g?.level||1)],['LEVEL',g?.level||1],['BOSS PHASE',g?.boss?.ph||'-'],['CAPITAL',b?.kind||'-'],['QUALITY',g?.settings?.quality||'-'],['FX',v?.fx?.length||0]].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div><div class="v9-debug-actions">${btn('GOD MODE','god')}${btn('×2 DAMAGE','damage2')}${btn('NORMAL DAMAGE','damage1')}${btn('+1000 CR','credits')}${btn('+1000 XP','xp')}${btn('SPAWN ENEMY','spawn-enemy')}${btn('SPAWN BOSS','spawn-boss')}${btn('NEXT SECTOR','next-sector')}</div>`}
  const keySeq=[];window.addEventListener('keydown',e=>{keySeq.push((e.key||'').toLowerCase());if(keySeq.length>10)keySeq.shift();if(keySeq.join('')==='v9debug')debugOpen()});
  rootInit();
  function rootInit(){ensureRoot();}
  hook(GameEngine.prototype,'setSetting',function(o,k,v,...a){const r=o.call(this,k,v,...a);if(V.persist?.settings)applySettings(V.persist.settings);return r});
  hook(GameEngine.prototype,'toMenu',function(o,...a){const r=o.apply(this,a);ensureRoot();$('v9Touch')?.classList.add('hidden');return r});
  hook(GameEngine.prototype,'startGame',function(o,...a){const r=o.apply(this,a);ensureRoot();V.openMap&&V.closeMap();v9TouchVisibility();const s=N8.v9.persist.settings||{};applySettings(s);return r});
  N8.post.push(g=>{g.v9Perf=g.v9Perf||{last:performance.now(),frameMs:16.7,fps:60};const now=performance.now();const ms=Math.max(.1,now-g.v9Perf.last);g.v9Perf.last=now;g.v9Perf.frameMs=g.v9Perf.frameMs*.9+ms*.1;g.v9Perf.fps=Math.round(1000/g.v9Perf.frameMs);ensureRoot();if(g.state===GAME.PLAYING&&g.v8?.t%20===0){v9TouchVisibility();const d=$('v9Debug');if(d&&!d.classList.contains('hidden'))renderDebug();const h=$('v9HudEvent');const e=g.v9?.event;if(h)h.textContent=e?.name||'WARFRONT ONLINE'}if(g.state!==GAME.PLAYING)$('v9Touch')?.classList.add('hidden')});
  /* Upgrade the old HUD's level label and attach a small v9 status strip without replacing v8 HUD. */
  hook(GameEngine.prototype,'updateHUD',function(o,...a){const r=o.apply(this,a);const g=this,lv=$('levelVal'),MAX=typeof MAX_LEVEL==='number'?MAX_LEVEL:10000;if(lv)lv.textContent=`${String(g.level).padStart(2,'0')} / ${MAX.toLocaleString()}`;const mode=$('modeVal');if(mode&&g.state===GAME.PLAYING)mode.textContent=(g.v9?.event?.name||'FRONTLINE').slice(0,20);const target=$('targetPanel')||$('targetInfo');const cap=g.v9?.capital;if(target&&cap&&!cap.dead){target.innerHTML=`<div class="target-name">${esc(cap.kind)} // CAPITAL SHIP</div><div class="target-bar"><i style="width:${Math.max(0,cap.hp/cap.maxHp*100)}%"></i></div><div class="target-meta">SHIELD ${Math.max(0,Math.round(cap.shield))} · HULL ${Math.max(0,Math.round(cap.hp))} · STAGE ${cap.stage}/4</div>`}return r});
  /* Command controls for module/customization inputs. */
  const root=$('v9Root');
  root?.addEventListener('click',e=>{const a=e.target.closest('[data-v9]')?.dataset.v9,g=G();if(a==='apply-custom'){const vals={primary:$('v9Primary')?.value,secondary:$('v9Secondary')?.value,engine:$('v9Engine')?.value,shield:$('v9Shield')?.value,emblem:$('v9Emblem')?.value?.trim()||'N',finish:$('v9Finish')?.value||'SATIN',trail:$('v9Trail')?.value||'ION'};for(const [k,v] of Object.entries(vals))V.customization.set(k,v,g);g?.toast('CUSTOMIZATION SAVED');renderCommand('customization')}if(['god','damage2','damage1','credits','xp','spawn-enemy','spawn-boss','next-sector'].includes(a)){if(a==='god'){N8.pilot.cheat=!N8.pilot.cheat;g?.toast(`GOD MODE ${N8.pilot.cheat?'ON':'OFF'}`)}if(a==='damage2')V.persist.debugDamage=2;if(a==='damage1')V.persist.debugDamage=1;if(a==='credits'){g.coins+=1000;N8.v9.saveAll(g)}if(a==='xp'){N8.addXP(g,1000,'DEBUG');N8.v9.saveAll(g)}if(a==='spawn-enemy'&&g.state===GAME.PLAYING)g.enemies.push(new Enemy(g.canvas.width/2,-50,g.level,'STANDARD','ELITE'));if(a==='spawn-boss'&&g.state===GAME.PLAYING&&!g.boss)g.boss=new Boss(g.canvas.width,g.level);if(a==='next-sector'&&g.state===GAME.PLAYING){g.completeLevel()}renderDebug()}});
  hook(GameEngine.prototype,'fire',function(o,...a){const old=V.persist.debugDamage||1,r=o.apply(this,a);if(this.player&&old!==1){const p=this.player;for(let i=Math.max(0,this.bullets.length-8);i<this.bullets.length;i++){const b=this.bullets[i];if(b&&!b.isEnemy&&!b._v9Scaled){b.damage*=old;b._v9Scaled=true}}}return r});
  /* Map rendering is event-driven; it never creates a second gameplay/render loop. */
})();

/* v15.1.1 deterministic asset registration */
window.NEBULA_BOOT?.asset('v9-ui.js');
